CREATE TABLE IF NOT EXISTS provinces (
        code TEXT NOT NULL PRIMARY KEY,
        name TEXT NOT NULL
);

INSERT INTO provinces (name, code) VALUES ("Vercelli", "VC");
INSERT INTO provinces (name, code) VALUES ("Novara", "NO");
INSERT INTO provinces (name, code) VALUES ("Cuneo", "CN");
INSERT INTO provinces (name, code) VALUES ("Asti", "AT");
INSERT INTO provinces (name, code) VALUES ("Alessandria", "AL");
INSERT INTO provinces (name, code) VALUES ("Biella", "BI");
INSERT INTO provinces (name, code) VALUES ("Verbano-Cusio-Ossola", "VB");
INSERT INTO provinces (name, code) VALUES ("Valle d'Aosta/Vallée d'Aoste", "AO");
INSERT INTO provinces (name, code) VALUES ("Varese", "VA");
INSERT INTO provinces (name, code) VALUES ("Como", "CO");
INSERT INTO provinces (name, code) VALUES ("Sondrio", "SO");
INSERT INTO provinces (name, code) VALUES ("Milano", "MI");
INSERT INTO provinces (name, code) VALUES ("Bergamo", "BG");
INSERT INTO provinces (name, code) VALUES ("Brescia", "BS");
INSERT INTO provinces (name, code) VALUES ("Pavia", "PV");
INSERT INTO provinces (name, code) VALUES ("Cremona", "CR");
INSERT INTO provinces (name, code) VALUES ("Mantova", "MN");
INSERT INTO provinces (name, code) VALUES ("Lecco", "LC");
INSERT INTO provinces (name, code) VALUES ("Lodi", "LO");
INSERT INTO provinces (name, code) VALUES ("Monza e della Brianza", "MB");
INSERT INTO provinces (name, code) VALUES ("Bolzano/Bozen", "BZ");
INSERT INTO provinces (name, code) VALUES ("Trento", "TN");
INSERT INTO provinces (name, code) VALUES ("Verona", "VR");
INSERT INTO provinces (name, code) VALUES ("Vicenza", "VI");
INSERT INTO provinces (name, code) VALUES ("Belluno", "BL");
INSERT INTO provinces (name, code) VALUES ("Treviso", "TV");
INSERT INTO provinces (name, code) VALUES ("Venezia", "VE");
INSERT INTO provinces (name, code) VALUES ("Padova", "PD");
INSERT INTO provinces (name, code) VALUES ("Rovigo", "RO");
INSERT INTO provinces (name, code) VALUES ("Udine", "UD");
INSERT INTO provinces (name, code) VALUES ("Gorizia", "GO");
INSERT INTO provinces (name, code) VALUES ("Trieste", "TS");
INSERT INTO provinces (name, code) VALUES ("Pordenone", "PN");
INSERT INTO provinces (name, code) VALUES ("Imperia", "IM");
INSERT INTO provinces (name, code) VALUES ("Savona", "SV");
INSERT INTO provinces (name, code) VALUES ("Genova", "GE");
INSERT INTO provinces (name, code) VALUES ("La Spezia", "SP");
INSERT INTO provinces (name, code) VALUES ("Piacenza", "PC");
INSERT INTO provinces (name, code) VALUES ("Parma", "PR");
INSERT INTO provinces (name, code) VALUES ("Reggio nell'Emilia", "RE");
INSERT INTO provinces (name, code) VALUES ("Modena", "MO");
INSERT INTO provinces (name, code) VALUES ("Bologna", "BO");
INSERT INTO provinces (name, code) VALUES ("Ferrara", "FE");
INSERT INTO provinces (name, code) VALUES ("Ravenna", "RA");
INSERT INTO provinces (name, code) VALUES ("Forlì-Cesena", "FC");
INSERT INTO provinces (name, code) VALUES ("Rimini", "RN");
INSERT INTO provinces (name, code) VALUES ("Massa-Carrara", "MS");
INSERT INTO provinces (name, code) VALUES ("Lucca", "LU");
INSERT INTO provinces (name, code) VALUES ("Pistoia", "PT");
INSERT INTO provinces (name, code) VALUES ("Firenze", "FI");
INSERT INTO provinces (name, code) VALUES ("Livorno", "LI");
INSERT INTO provinces (name, code) VALUES ("Pisa", "PI");
INSERT INTO provinces (name, code) VALUES ("Arezzo", "AR");
INSERT INTO provinces (name, code) VALUES ("Siena", "SI");
INSERT INTO provinces (name, code) VALUES ("Grosseto", "GR");
INSERT INTO provinces (name, code) VALUES ("Prato", "PO");
INSERT INTO provinces (name, code) VALUES ("Perugia", "PG");
INSERT INTO provinces (name, code) VALUES ("Terni", "TR");
INSERT INTO provinces (name, code) VALUES ("Pesaro e Urbino", "PU");
INSERT INTO provinces (name, code) VALUES ("Ancona", "AN");
INSERT INTO provinces (name, code) VALUES ("Macerata", "MC");
INSERT INTO provinces (name, code) VALUES ("Ascoli Piceno", "AP");
INSERT INTO provinces (name, code) VALUES ("Fermo", "FM");
INSERT INTO provinces (name, code) VALUES ("Viterbo", "VT");
INSERT INTO provinces (name, code) VALUES ("Rieti", "RI");
INSERT INTO provinces (name, code) VALUES ("Roma", "RM");
INSERT INTO provinces (name, code) VALUES ("Latina", "LT");
INSERT INTO provinces (name, code) VALUES ("Frosinone", "FR");
INSERT INTO provinces (name, code) VALUES ("L'Aquila", "AQ");
INSERT INTO provinces (name, code) VALUES ("Teramo", "TE");
INSERT INTO provinces (name, code) VALUES ("Pescara", "PE");
INSERT INTO provinces (name, code) VALUES ("Chieti", "CH");
INSERT INTO provinces (name, code) VALUES ("Campobasso", "CB");
INSERT INTO provinces (name, code) VALUES ("Isernia", "IS");
INSERT INTO provinces (name, code) VALUES ("Caserta", "CE");
INSERT INTO provinces (name, code) VALUES ("Benevento", "BN");
INSERT INTO provinces (name, code) VALUES ("Napoli", "NA");
INSERT INTO provinces (name, code) VALUES ("Avellino", "AV");
INSERT INTO provinces (name, code) VALUES ("Salerno", "SA");
INSERT INTO provinces (name, code) VALUES ("Foggia", "FG");
INSERT INTO provinces (name, code) VALUES ("Bari", "BA");
INSERT INTO provinces (name, code) VALUES ("Taranto", "TA");
INSERT INTO provinces (name, code) VALUES ("Brindisi", "BR");
INSERT INTO provinces (name, code) VALUES ("Lecce", "LE");
INSERT INTO provinces (name, code) VALUES ("Barletta-Andria-Trani", "BT");
INSERT INTO provinces (name, code) VALUES ("Potenza", "PZ");
INSERT INTO provinces (name, code) VALUES ("Matera", "MT");
INSERT INTO provinces (name, code) VALUES ("Cosenza", "CS");
INSERT INTO provinces (name, code) VALUES ("Catanzaro", "CZ");
INSERT INTO provinces (name, code) VALUES ("Reggio di Calabria", "RC");
INSERT INTO provinces (name, code) VALUES ("Crotone", "KR");
INSERT INTO provinces (name, code) VALUES ("Vibo Valentia", "VV");
INSERT INTO provinces (name, code) VALUES ("Trapani", "TP");
INSERT INTO provinces (name, code) VALUES ("Palermo", "PA");
INSERT INTO provinces (name, code) VALUES ("Messina", "ME");
INSERT INTO provinces (name, code) VALUES ("Agrigento", "AG");
INSERT INTO provinces (name, code) VALUES ("Caltanissetta", "CL");
INSERT INTO provinces (name, code) VALUES ("Enna", "EN");
INSERT INTO provinces (name, code) VALUES ("Catania", "CT");
INSERT INTO provinces (name, code) VALUES ("Ragusa", "RG");
INSERT INTO provinces (name, code) VALUES ("Siracusa", "SR");
INSERT INTO provinces (name, code) VALUES ("Sassari", "SS");
INSERT INTO provinces (name, code) VALUES ("Nuoro", "NU");
INSERT INTO provinces (name, code) VALUES ("Cagliari", "CA");
INSERT INTO provinces (name, code) VALUES ("Oristano", "OR");
INSERT INTO provinces (name, code) VALUES ("Olbia-Tempio", "OT");
INSERT INTO provinces (name, code) VALUES ("Ogliastra", "OG");
INSERT INTO provinces (name, code) VALUES ("Medio Campidano", "VS");
INSERT INTO provinces (name, code) VALUES ("Carbonia-Iglesias", "CI");
